sudo: required
services:
  - docker

before_install:

#This will build the docker file from client folder and given the tag

  - docker build -t kathpalrk/react-redis-postgres-travis -f ./client/Dockerfile.dev ./client

script:
  - docker run kathpalrk/react-redis-postgres-travis npm test -- --coverage --watchAll=false

  ###This line belongs whether the test is being passed or not then you may proceed further in next line  

after_success:
  - docker build -t rahulkathpal/multi-client ./client
  - docker build -t rahulkathpal/multi-nginx  ./nginx
  - docker build -t rahulkathpal/multi-server ./server
  - docker build -t rahulkathpal/multi-worker ./worker

###Now let's move these images into DockerHUB.
#but before that login to Docker HUB which we need to declare here in Encrypted enviornment which we need to declare under Travis with DOCKER_ID and DOCKER_PASSWORD in TRavis Env variable
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ###Now Our docker has been logged in from Standard input from Docker password and let's declare the push into docker hub
  - docker push rahulkathpal/multi-client
  - docker push rahulkathpal/multi-nginx
  - docker push rahulkathpal/multi-server
  - docker push rahulkathpal/multi-worker 
